#8 - added new script param: --nmap-nse, minor updates - signed-off-by: trimstray <trimstray@gmail.com>

diff --git a/src/__init__ b/src/__init__
--- a/src/__init__
+++ b/src/__init__
@@ -67,6 +67,9 @@ function __main__() {
   # Default 'mixed-content' variable.
   local mixed_content_state="0"
 
+  # Default 'nmap-nse' variable.
+  local nmap_nse_state="0"
+
   # Set redirects limit.
   local max_redirects_state="0"
   local _redirects=10
@@ -129,7 +132,7 @@ function __main__() {
   # Specifies the call parameters of the script, the exact description
   # can be found in _help_ and file README.md.
   local _short_opt="d:sh"
-  local _long_opt="help,domain:,ssl,headers,scan:,mixed-content,max-redirects:,user-agent:"
+  local _long_opt="help,domain:,ssl,headers,scan:,mixed-content,nmap-nse,max-redirects:,user-agent:"
 
   _GETOPT_PARAMS=$(getopt -o "${_short_opt}" --long "${_long_opt}" \
                    -n "${_init_name}" -- "${__script_params[@]}")
@@ -190,6 +193,12 @@ function __main__() {
       --mixed-content)
 
         export mixed_content_state=1
+
+        shift ;;
+
+      --nmap-nse)
+
+        export nmap_nse_state=1
 
         shift ;;
 
@@ -508,6 +517,27 @@ function __main__() {
         tput sgr0
 
       fi
+
+    fi
+
+    echo
+
+  fi
+
+if [[ "$nmap_nse_state" -eq 1 ]] ; then
+
+    DomainStrip "$_http_last"
+
+    # shellcheck disable=SC2154
+    _init_function "DomainNmapNse \"${_domain_name}\" \"${_remote_port}\""
+
+    _fstate="$?"
+
+    if [[ "$_fstate" -ne 0 ]] ; then
+
+      # shellcheck disable=SC2086,SC2154
+      printf '\r\n    \e['${e_trgb}'m%s\e[m\n\n' "Connection error"
+      tput sgr0
 
     fi
 
