#24 - the testssl.sh scanning mechanism, minor updates - signed-off-by: trimstray <trimstray@gmail.com>

diff --git a/src/__init__ b/src/__init__
--- a/src/__init__
+++ b/src/__init__
@@ -57,6 +57,10 @@ function __main__() {
   # Default 'ssl' variable.
   local ssl_state="0"
 
+  # Default 'ssl test' variable.
+  local ssl_test_state="0"
+  local _last_http_scheme="http"
+
   # Default 'headers' variable.
   local headers_state="0"
 
@@ -89,7 +93,7 @@ function __main__() {
   # unnecessarily run.
   readonly commands=(basename dirname stat ps date grep cut sed awk chown \
                      chmod mkdir curl openssl dig geoiplookup bc \
-                     observatory ssllabs-scan mixed-content-scan nmap)
+                     testssl.sh observatory ssllabs-scan mixed-content-scan nmap)
 
   # If you intend to specify the full path to the command we do it like:
   # readonly exec_gzip="/bin/gzip"
@@ -138,8 +142,8 @@ function __main__() {
 
   # Specifies the call parameters of the script, the exact description
   # can be found in _help_ and file README.md.
-  local _short_opt="d:sh"
-  local _long_opt="help,domain:,ssl,headers,scan:,mixed-content,nse,user-agent:,max-redirects:,timeout:"
+  local _short_opt="d:sth"
+  local _long_opt="help,domain:,ssl,ssl-test,headers,scan:,mixed-content,nse,user-agent:,max-redirects:,timeout:"
 
   _GETOPT_PARAMS=$(getopt -o "${_short_opt}" --long "${_long_opt}" \
                    -n "${_init_name}" -- "${__script_params[@]}")
@@ -180,6 +184,12 @@ function __main__() {
       -s|--ssl)
 
         export ssl_state=1
+
+        shift ;;
+
+      -t|--ssl-test)
+
+        export ssl_test_state=1
 
         shift ;;
 
@@ -432,6 +442,31 @@ function __main__() {
     fi
 
   done
+
+  echo
+
+  # shellcheck disable=SC2154
+  if [[ "$_last_http_scheme" == "https" ]] ; then
+
+    if [[ "$ssl_test_state" -eq 1 ]] ; then
+
+      DomainStrip "$_http_last"
+
+      _init_function "DomainTestSsl \"$_domain_name\""
+
+      _fstate="$?"
+
+      if [[ "$_fstate" -ne 0 ]] ; then
+
+        # shellcheck disable=SC2086,SC2154
+        printf '\r\n    \e['${e_trgb}'m%s\e[m\n\n' "Connection error"
+        tput sgr0
+
+      fi
+
+    fi
+
+  fi
 
   echo
 
