#68 - updated script args; added sublist3r_state parser - signed-off-by: trimstray <trimstray@gmail.com>

diff --git a/src/__init__ b/src/__init__
--- a/src/__init__
+++ b/src/__init__
@@ -112,6 +112,9 @@ function __main__() {
   # Default 'waf' variable.
   local waf_state="0"
 
+  # Default 'sublist3r' variable.
+  local sublist3r_state="0"
+
   # Default 'cache-bypass' variable.
   local cache_bypass_state="0"
   local cache_bypass_type=""
@@ -193,7 +196,7 @@ function __main__() {
   # Specifies the call parameters of the script, the exact description
   # can be found in _help_ and file README.md.
   local _short_opt="u:shbM:H:p:"
-  local _long_opt="help,version,url:,ssl,headers,body,req-method:,req-header:,proxy:,testssl,observatory,ssllabs,mixed-content,nse,waf,cache-bypass:,user-agent:,max-redirects:,timeout:,hide-src-ip"
+  local _long_opt="help,version,url:,ssl,headers,body,req-method:,req-header:,proxy:,testssl,observatory,ssllabs,mixed-content,nse,waf,dns,cache-bypass:,user-agent:,max-redirects:,timeout:,hide-src-ip"
 
   _GETOPT_PARAMS=$(getopt -o "${_short_opt}" --long "${_long_opt}" \
                    -n "${_init_name}" -- "${__script_params[@]}")
@@ -313,6 +316,12 @@ function __main__() {
       --waf)
 
         export waf_state=1
+
+        shift ;;
+
+      --dns)
+
+        export sublist3r_state=1
 
         shift ;;
 
@@ -1099,12 +1108,44 @@ function __main__() {
 
   fi
 
-if [[ "$waf_state" -eq 1 ]] ; then
+  if [[ "$waf_state" -eq 1 ]] ; then
 
     DomainStrip "$_http_last"
 
     # shellcheck disable=SC2154
     _init_function "DomainScanWhatWaf \"${_http_proto}${_domain_name}\""
+
+    _fstate="$?"
+
+    if [[ "$_fstate" -ne 0 ]] ; then
+
+      # shellcheck disable=SC2086,SC2154
+      if [[ "$HTRACE_COLORS" == "off" ]] ; then
+
+        # shellcheck disable=SC2086,SC2154
+        printf '\r\n    %s\n\n' "Connection error"
+
+      else
+
+        # shellcheck disable=SC2086,SC2154
+        printf '\r\n    \e['${e_trgb}'m%s\e[m\n\n' "Connection error"
+
+      fi
+
+      tput sgr0
+
+    fi
+
+    echo
+
+  fi
+
+  if [[ "$sublist3r_state" -eq 1 ]] ; then
+
+    DomainStrip "$_http_last"
+
+    # shellcheck disable=SC2154
+    _init_function "DomainScanSublist3r \"${_domain_name}\""
 
     _fstate="$?"
 
